replicaCount: 1
image:
  registry: "ghcr.io"
  repository: vhula/uvbot
  tag: "v1.0.0-2c10a0b"
  os: linux
  arch: amd64
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
pullPolicy: IfNotPresent
secret:
  name: uvbot
  env: TELE_TOKEN
  key: token
securityContext:
  privileged: true
