replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
image:
  registry: "ghcr.io"
  repository: vhula/uvbot
  tag: "0.0.1-8c0e7ff"
  os: linux
  arch: amd64
  pullPolicy: IfNotPresent
secret:
  name: uvbot
  env: TELE_TOKEN
  key: token
securityContext:
  privileged: true
