name: UV Bot Pipeline

on: push

jobs:
  ci:
    name: UV Bot CI Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: make test
      - name: Build docker image
        run: make image
