name: UV Bot Pipeline

on:
  push:
    branches:
      - develop

env:
  ARCH: amd64
  OS: linux
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    name: UV Bot CI Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      repository-projects: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: make image REGISTRY=$REGISTRY IMAGE_NAME=$IMAGE_NAME TARGETARCH=$ARCH TARGETOS=$OS

      - name: Publish docker image
        run: make push REGISTRY=$REGISTRY IMAGE_NAME=$IMAGE_NAME TARGETARCH=$ARCH TARGETOS=$OS

  cd:
    name: UV Bot CD Job
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - run: echo "CHART_VERSION=$(yq -r '.version' helm/Chart.yaml)" >> $GITHUB_ENV

      - run: echo "NEXT_CHART_VERSION=$(echo ${CHART_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: |
                yq -i eval '.image.tag = strenv(VERSION)' helm/values.yaml

      - uses: mikefarah/yq@master
        with:
          cmd: |
                yq -i eval '.version = strenv(NEXT_CHART_VERSION)' helm/Chart.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push