name: UV Bot Pipeline

on:
  push:
    branches:
      - develop

env:
  ARCH: amd64
  OS: linux
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    name: UV Bot CI Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      repository-projects: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: make image REGISTRY=$REGISTRY IMAGE_NAME=$IMAGE_NAME TARGETARCH=$ARCH TARGETOS=$OS

      - name: Publish docker image
        run: make push REGISTRY=$REGISTRY IMAGE_NAME=$IMAGE_NAME TARGETARCH=$ARCH TARGETOS=$OS
